### ISSUE TITLE
Add emails + SMS for new template types

### ISSUE THREAD

**Issue by cschlessinger** [SFDigitalServices/vaccination-distribution#14]
Create placeholder email and SMS templates for the following templates:

- Confirmation + eligibility, healthcare workers
- Confirmation, under 16
- Confirmation, future phases

**Comment by hshaosf** [comment]
Base on the spec here at https://github.com/SFDigitalServices/vaccination-distribution/issues/10  I think we need one for 65+ too.

**Comment by cschlessinger** [comment]
People 65+ will get the generic confirmation notification and the generic eligibility notification at the same time

**Comment by hshaosf** [comment]
Thanks @cschlessinger! I will make the change to calculation logic to reflect that.

**Comment by josh-chou** [comment]
https://github.com/SFDigitalServices/vaccination-distribution/pull/19
This PR adds support the the subtype, but it didn't add any templates.
The template should follow the pattern of templates/{email or sms}/{notificationtype}_{subtype}_{lang}.txt
I will create a new PR to add the new subtype templates listed above.

**Comment by josh-chou** [comment]
https://github.com/SFDigitalServices/vaccination-distribution/pull/33

**Comment by hshaosf** [comment]
@cschlessinger  Do we need a template for ones that don't have a phase yet?

**Comment by cschlessinger** [comment]
@hshaosf yes, they get a special email https://docs.google.com/document/d/1GGVuqTOsdrg2pQVe_Bgzex97mrEhYWGdLLoxZHalP_E/edit#heading=h.jjgpzzv3d9r7

**Comment by hshaosf** [comment]
Thank you! Ah, I see that is named `FUTURE` in SubType.
