### ISSUE TITLE
Send notifications based on the language the user selects in the form

### ISSUE THREAD

**Issue by cschlessinger** [SFDigitalServices/vaccination-distribution#21]
Given that I submitted a signup form
And I selected a language other than English in response to the question "What language do you want us to use when we send you a notification?"
Then I receive my confirmation notification in the language I selected
And I receive my eligibility notification in the language I selected

**Comment by josh-chou** [comment]
We are already doing this in 
https://github.com/SFDigitalServices/vaccination-distribution/blob/35350ab17ce3a420ab116c1bc645235145cde293/service/resources/notifications.py#L79-L85

and

https://github.com/SFDigitalServices/vaccination-distribution/blob/35350ab17ce3a420ab116c1bc645235145cde293/service/resources/notifications.py#L162-L166
