### ISSUE TITLE
Map internal phase tiers to public-facing terms

### ISSUE THREAD

**Issue by cschlessinger** [SFDigitalServices/vaccination-distribution#30]
In emails, we need to have phases and tiers that map to the public's expectations, even though we're doing some hacky stuff to create unofficial sub-tiers in the code to handle special cases like 65+ being eligible despite their phase/tier not being eligible.

1A-1 -> Phase 1A (healthcare workers)
1A-2 -> Phase 1A (people who live in nursing homes)
1B-1-1 -> Phase 1B Tier 1 (people 65+)
1B-1-2 -> Phase 1B Tier 1 (people who work in person in childcare/ed, food + ag, emergency services)
1B-2 -> Phase 1B Tier 2 (work in person in manufacturing, transportation, industrial/commercial; or live in congregate setting)
1C -> Phase 1C (people who work in a number of industries in person, are 50-64, or any age with qualifying health conditions)

Please put the text in parenthesis in a comment next to the mapping so we can keep track of what's what and reduce likelihood of mapping errors

**Comment by cschlessinger** [comment]
Since the human-facing text won't be stored in the database, can we translate it? Where do you think this mapping might live?

**Comment by hshaosf** [comment]
I'll put them into the calculator since those machine values are there as well.
