### ISSUE TITLE
Env vars to store current phases

### ISSUE THREAD

**Issue by cschlessinger** [SFDigitalServices/vaccination-distribution#4]
One env var to store the CURRENT_PHASE (string)
Another env var to store all ACTIVE_PHASES (array)

**Comment by hshaosf** [comment]
@cschlessinger Do we need to consider the Tiers under each Phase? Such as 1B Tier One?

**Comment by cschlessinger** [comment]
@hshaosf I'm in the process of trying to figure that out now!
